{{- if .Values.gcp }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - {{ .Values.api_host }}
    - {{ .Values.socketcluster_host }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: httpsredirect
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}
